### ISSUE TITLE
make public constructor for GuiListener

### ISSUE THREAD

**Issue by rexlManu** [Jannyboy11/GuiLib#1]
title^^

**Comment by Jannyboy11** [comment]
I needed to make the GuiListener a single instance to work around a bug in CraftBukkit/Spigot 1.13. Read more about it here: [https://www.spigotmc.org/resources/guilib.59054/update?update=242426]( https://www.spigotmc.org/resources/guilib.59054/update?update=242426). The commit that changed the constructor to private also had a minor version bump to indicate this small breaking change.
