### ISSUE TITLE
sorry for my last issues.

### ISSUE THREAD

**Issue by rexlManu** [Jannyboy11/GuiLib#2]
So I think your Gui Lib API is pretty bad. You absolutely do not know how to work with her. Besides, you can not use it because it was made for 1.13 & Java 10. And nobody uses these versions. Well otherwise she looks pretty chic. Vlt will be something out of it.

**Comment by Jannyboy11** [comment]
Right so the application programming interface is bad because users use outdated versions of Minecraft and Java? Could you elaborate on that please? Java 11 will be released this month and it'll be the new LTS release so I see no reason to downgrade.

**Comment by jord1e** [comment]
https://github.com/Jordieh/GuiLib/tree/java-8 (Java 8 compatibility 😉)

**Comment by Jannyboy11** [comment]
Honestly you don't even need a fork for java 8 compatability. Java is backwards compatabile. You can upgrade your runtime and still run classes that were compiled for older versions. I'm closing this issue.
