### ISSUE TITLE
Get amount of items were given from the ItemStack in SuccessFulTransferCallback

### ISSUE THREAD

**Issue by assada** [Jannyboy11/GuiLib#8]
How to get the number of items that fit into the player's inventory?

```java
        @Override
        public void afterTransfer(MenuHolder menuHolder, InventoryClickEvent inventoryClickEvent, ItemStack itemStack) {
            ClaimItemsMenu.this.shiftButtons(inventoryClickEvent.getSlot());
      
            Bukkit.getLogger().warning("[Plugin] %d items in player inventory and %d still in claim menu!".formatted() // ???
            );
        }
```
![telegram-cloud-photo-size-2-5399843505888672165-x](https://user-images.githubusercontent.com/1472664/148982953-614e956b-1af2-4ae7-9041-bf77b7c104ad.jpg)

In this case only 2 diamonds will be transferred from menu to user inventory.

**Comment by assada** [comment]
Ok. There is no simple way to find out this =(

**Comment by Jannyboy11** [comment]
You can use the result of Inventory#addItem. It returns a Map<ItemStack, Integer> which specifies how many items were NOT transferred. You should be able to calculate how many items were transferred using some simple subtraction math.
